# Generated by Django 3.1.4 on 2021-03-15 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('dated', models.DateField(null=True)),
                ('createddate', models.DateField(null=True)),
                ('salutation', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=100)),
                ('introduction', models.TextField()),
                ('closing', models.TextField()),
                ('signature', models.CharField(max_length=100)),
                ('termsnconditions', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='quotations.client')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('size', models.CharField(blank=True, max_length=50)),
                ('quantity', models.IntegerField()),
                ('rate', models.FloatField()),
                ('hsncode', models.CharField(blank=True, max_length=30)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='quotations.quotation')),
            ],
        ),
    ]
