# Generated by Django 3.1.4 on 2021-03-14 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=models.CharField(blank=True, default=12122312, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='district',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('subject', models.CharField(max_length=100)),
                ('headmessege', models.TextField()),
                ('footmessege', models.TextField()),
                ('termsnconditions', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='quotations.client')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('size', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('rate', models.FloatField()),
                ('hsncode', models.CharField(max_length=30)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='quotations.quotation')),
            ],
        ),
    ]
