# Generated by Django 3.1.4 on 2021-03-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_auto_20210315_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='district',
        ),
        migrations.RemoveField(
            model_name='client',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='client',
            name='state',
        ),
    ]
